import Container from "../Components/container"
import LoginCss from "../../styles/login.module.css"

import Image from "next/legacy/image"
import Link from "next/link"
import Head from "next/head"

import Navbar from "../Components/Navbar"
import Footer from "../Components/footer"


const login = () => {

    const css = {width: "100%", height: "auto" }

    return(
        <>
            <Head>   
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" type="" href="/img/favicon.png" />    
            </Head>

            <Navbar />

            <Container>
                <div id={LoginCss.login_logo} className="text-center">
                    <Image width="200" height="60" layout="intrinsic" style={css} src="/img/logo.png" alt="" />
                </div>

                <div id={LoginCss.login_form}>
                    <form action="">
                        <div className="row">
                            <div className="col-lg-3"></div>
                            <div className="col-lg-6">
                                <div id={LoginCss.full_form}>
                                    
                                    <label htmlFor="email" className="mt-4">Email*</label>
                                    <input type="email" className="form-control" id="email" placeholder="Email" />
                                    
                                    <label htmlFor="password" className="mt-4">Password*</label>
                                    <input type="password" className="form-control" id="password" placeholder="Password" />
                                    
                                    <input className="mt-4" type="checkbox" name="" id="" /> <span> Remember Me</span>

                                    <button type="submit" className="btn" id={LoginCss.signup_btn}>Login</button>

                                    <Link href="/forget-password">
                                        <h6 className="mt-4">Forget Password</h6>
                                    </Link>

                                    <p className="text-center mt-4">or</p>

                                    <div className="row text-center" id={LoginCss.login_app_logo}>
                                        <div className="col-lg-6 mt-3">
                                            <Link href="">
                                                <Image width="200" height="50" layout="intrinsic" style={css} src="/img/google.png" alt="" />
                                            </Link>
                                        </div>
                                        <div className="col-lg-6 mt-3">
                                            <Link href="">
                                                <Image width="200" height="50" layout="intrinsic" style={css} src="/img/facebook.png" alt="" />
                                            </Link>
                                        </div>
                                    </div>

                                    <div className="text-center mt-4">
                                    <p>Do not have an account ? <Link href="/sign-up">Register</Link></p>
                                    </div>
                                </div>

                            </div>
                            <div className="col-lg-3"></div>
                        </div>
                    </form>
                </div>

            </Container>

            <Footer />
        </>
    )
}

export default login