import Container from "../Components/container"
import SignupCss from "../../styles/sign-up.module.css"

import Image from "next/legacy/image"
import Link from "next/link"
import Head from "next/head"

import Navbar from "../Components/Navbar"
import Footer from "../Components/footer"


const signup = () => {

    const css = {width: "100%", height: "auto" }

    return(
        <>

            <Head>   
                <title>Sign up</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" type="" href="/img/favicon.png" />     
            </Head>

            <Navbar />

            <Container>
                <div id={SignupCss.signup_logo} className="text-center">
                    <Image width="200" height="60" layout="intrinsic" style={css} src="/img/logo.png" alt="" />
                </div>

                <div id={SignupCss.signup_form}>
                    <form action="">
                        <div className="row">
                            <div className="col-lg-3"></div>
                            <div className="col-lg-6">
                                <div id={SignupCss.full_form}>
                                    <label htmlFor="name" className="mt-4">Name*</label>
                                    <input type="text" className="form-control" id="name" placeholder="Name" />
                                    <label htmlFor="email" className="mt-4">Email*</label>
                                    <input type="email" className="form-control" id="email" placeholder="Email" />
                                    <label htmlFor="phone" className="mt-4">Phone*</label>
                                    <input type="tel" className="form-control" id="phone" placeholder="Phone" />
                                    <label htmlFor="profile-ficture" className="mt-4">Profile Picture</label>
                                    <input type="file" className="form-control" id="profile-ficture" />
                                    <label htmlFor="password" className="mt-4">Password*</label>
                                    <input type="password" className="form-control" id="password" placeholder="Password" />


                                    <button type="submit" className="btn" id={SignupCss.signup_btn}>Sign Up</button>

                                    <div className="text-center mt-4">
                                        <Link href="/login">Back to Login</Link>
                                    </div>
                                </div>

                            </div>
                            <div className="col-lg-3"></div>
                        </div>
                    </form>
                </div>
            </Container>

            <Footer />
        </>
    )
}

export default signup