import Head from 'next/head'
import Link from 'next/link';

import freeTrialCss from '../../styles/free_trial.module.css'
import Container from '../Components/container'

import Navbar from "../Components/Navbar";
import Footer from "../Components/footer";
import FreetrialForm from '../Components/quote_and_trial_form'


const freeTrial = () => {
    return (
        <>
            <Head>
                <title>Free Trial</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <Navbar />

            <Container>
                <div id={freeTrialCss.free_trial_page}>
                    <div className="row">
                        <div className="col-lg-6">
                            <h1>Free trial</h1>
                            <h4>THE BEST PHOTO EDITING SERVICE COMPANY YOU BE THE JUDGE.</h4>
                            <h2>INSTRUCTION</h2>
                            <h5>How to fill up the free trial form</h5>
                            <p><i className="fa-solid fa-paper-plane"></i> You can upload up to two files for a Free Trial</p>
                            <p><i className="fa-solid fa-paper-plane"></i> If your image file size exceeds this limit please mail us.</p>
                            <h5>In case the page is loading slowly:</h5>
                            <p><i className="fa-solid fa-paper-plane"></i> Please refresh the page, or</p>
                            <p><i className="fa-solid fa-paper-plane"></i> Contact Us for any queries.</p>
                            <p>We have 24/7 customer support. For any kind of free trial problem please Go to contact us.</p>
                        </div>
                        <div className="col-lg-6">
                            <FreetrialForm buttonText="Free Trial" />
                        </div>
                    </div>
                </div>
            </Container>

            <Footer/>
        </>
    )
}

export default freeTrial