import Head from "next/head"
import Link from "next/link"

import Container from "../Components/container"
import Navbar from "../Components/Navbar"
import Footer from "../Components/footer"

import helpCss from "../../styles/help.module.css"


const help = () => {
    return (
        <>
            <Head>
                <title>FAQ</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <Navbar />

            <Container>

                <div id={helpCss.first_section}>
                    <h1 className="text-center">Coming Soon . . . .</h1>
                </div>

            </Container>

            <Footer />
        </>
    )
}

export default help