import Link from "next/link";
import Head from "next/head";
import Image from "next/legacy/image"

import Container from "../Components/container"
import AboutCss from "../../styles/about.module.css"

import Navbar from "../Components/Navbar"
import Footer from "../Components/footer";

const about = () => {

    const css = {width: "100%", height: "auto" }

    return (
        <>

            <Head>
                <title>About Us</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />  
            </Head>

            <Navbar />

            <Container>
                <div id={AboutCss.about_first}>
                    <div className="row">
                        <div className="col-lg-7">
                            <h1>About Us</h1>
                            <h4>Welcome to Clipping Path Graphics</h4>
                            <p>Clipping Path Graphics Founded in 2012 with having the vision of image editing services around the world. You are always welcome if you need quality, satisfactory work, skilled and professional designers. Especially quick time turnaround service, long-term business relationships by the need of your online business or e-commerce image editing services. “Clipping path graphics” is a very well-known image editing company in the field of the international marketplace like online shops & e-commerce businesses.</p>
                        </div>
                        <div className="col-lg-5">
                            <Image width="200" height="190" layout="responsive" style={css} src="/img/banner-img.webp" alt="" />
                        </div>
                    </div>
                </div>

                <div id={AboutCss.about_two}>
                        <div className="row d-flex align-items-center">
                            <div className="col-lg-6">
                                <Image width="200" height="140" layout="responsive" style={css} src="/img/about-work.svg" alt="" />
                            </div>
                            <div className="col-lg-6">
                                <h3>Our Services</h3>
                                <p>It offers you a confirmed qualitative service supported image editing material activities particularly Clipping Path | Background Removal Service | Image Shadow Making | Retouching Service | Ghost Mannequin service and plenty of additional artistic service as per our respectful client’s provided directions.</p>
                                <p>CPG highly qualified and several other years intimate graphics designer is appointed to our clipping path service company to confirm our purchaser’s heart’s content. There’s no unmixed smart however our licensed personnel is devoted to supplying 100 percent quality and that I hope you may be fallen enamored and affected by our hand-woven pure services.</p>
                                <p>Our regular payment structure is stronger than the other company provided, therefore it’s been straightforward to induce skilled buddies to induce engaged in our company who are happy. A graphics designer is appointed to our clipping path service company to confirm our purchaser’s heart’s content.</p>
                            </div>
                        </div>
                </div>

                <div id={AboutCss.about_three}>
                        <div className="row d-flex align-items-center">
                            <div className="col-lg-7">
                                <h4>SIMPLY EXPRESS TO EVERY ONE OF US. THE NECESSITIES YOU NEED TO DO AND AFTERWARD BE WITHOUT PRESSURE. YOU WILL COMPLETE THE ERRAND 100% EXACT IN TIME AS WE HAVE MORE THAN 150 TALENTED VISUAL PLANNERS WHO WORK DAY IN AND DAY OUT FOR YOUR SERVICE.</h4>
                            </div>
                            <div className="col-lg-5 text-center">
                                <Image width="280" height="250" layout="intrinsic" style={css} src="/img/express.webp" alt="" />
                            </div>
                        </div>
                </div>

                <div id={AboutCss.about_four}>
                        <h3 className="text-center">Why You Choose Us?</h3>
                        <div className="row text-center">
                            <div className="col-lg-6">
                                <ul>
                                    <li>Branding Your Business</li>
                                    <li>Save Your Time</li>
                                    <li>Save Your Money</li>
                                    <li>Enhancing Efficiency And Productivity</li>
                                </ul> 
                            </div>
                            <div className="col-lg-6">
                                <ul>
                                    <li>Low Cost Facilities</li>
                                    <li>Top Quality Delivery</li>
                                    <li>Free Trial Option</li>
                                    <li>Bulk Image Processing</li>
                                </ul> 
                            </div>
                        </div>
                </div>

            </Container>

            <Footer />
        </>
    )
}

export default about