import Head from 'next/head'
import Image from 'next/legacy/image'
import Link from "next/link";

import offerCss from '../../styles/offer.module.css'

import Navbar from '../Components/Navbar';
import Footer from '../Components/footer';
import Form from "../Components/offer_form"
import Container from '../Components/container'


const offer = () => {

    const css = {width: "100%", height: "auto" }

    return (
        <>

            <Head>   
                <title>Our Offer</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" /> 
            </Head>

            <Navbar />

            <Container>
                <div id={offerCss.offer_page}>
                    <div id={offerCss.offer_first}>
                        <div className="row">
                            <div className="col-lg-7">
                                <h1>Send Us Offer</h1>
                                <p>Wanna know if we are the photo editing company you are looking for ?</p>
                                <h4>Get a free trial now.</h4>

                                <div className="mt-5">
                                    <Link href="/get-a-quote" className='btn btn-lg' id={offerCss.quote}>Get Started <i class="fa-solid fa-arrow-right"></i></Link>
                                    <Link href="/free-trial" className='btn btn-lg' id={offerCss.trial}>Get Free Trial</Link>
                                </div>

                            </div>
                            <div className="col-lg-5 text-center">
                                <Image width="500" height="250" layout="intrinsic" style={css} src="/img/offer.png" alt="" />
                            </div>
                        </div>
                    </div>

                    <div id={offerCss.offer_second}>
                        <div className="row d-flex align-items-center">
                            <div className="col-lg-5 text-end">
                                <h3>Get your custom quote <br /> in 30 Minutes</h3>
                            </div>
                            <div className="col-lg-7">
                                <p>We at Clipping Path Studio enable our global clients to grow their businesses by providing hand-drawn, high-quality, affordable photoshop services.</p>
                            </div>
                        </div>
                    </div>

                    <div id={offerCss.offer_third}>
                        <div className="row">
                            <div className="col-lg-8">
                                <div id={offerCss.offer_left}>
                                    <h2>What can we help you with ?</h2>
                                    <p>Choose the services you need help with by ticking the box below.</p>

                                    <div className="row">
                                        <div className="col-lg-3 col-md-6">
                                            <div className="form-check">
                                                <input className="form-check-input mt-3" type="checkbox" value="" id="" />
                                                <label className="form-check-label mt-3" for="">
                                                    Clipping Path
                                                </label>
                                            </div>
                                        </div>
                                        <div className="col-lg-3 col-md-6">
                                            <div className="form-check">
                                                <input className="form-check-input mt-3" type="checkbox" value="" id="" />
                                                <label className="form-check-label mt-3" for="">
                                                    Background Removal
                                                </label>
                                            </div>
                                        </div>
                                        <div className="col-lg-3 col-md-6">
                                            <div className="form-check">
                                                <input className="form-check-input mt-3" type="checkbox" value="" id="" />
                                                <label className="form-check-label mt-3" for="">
                                                    Image Masking
                                                </label>
                                            </div>
                                        </div>
                                        <div className="col-lg-3 col-md-6">
                                            <div className="form-check">
                                                <input className="form-check-input mt-3" type="checkbox" value="" id="" />
                                                <label className="form-check-label mt-3" for="">
                                                    Photo Retoching
                                                </label>
                                            </div>
                                        </div>
                                        <div className="col-lg-3 col-md-6">
                                            <div className="form-check">
                                                <input className="form-check-input mt-3" type="checkbox" value="" id="" />
                                                <label className="form-check-label mt-3" for="">
                                                    Shadow
                                                </label>
                                            </div>
                                        </div>
                                        <div className="col-lg-3 col-md-6">
                                            <div className="form-check">
                                                <input className="form-check-input mt-3" type="checkbox" value="" id="" />
                                                <label className="form-check-label mt-3" for="">
                                                    Vector Conversion
                                                </label>
                                            </div>
                                        </div>
                                        <div className="col-lg-3 col-md-6">
                                            <div className="form-check">
                                                <input className="form-check-input mt-3" type="checkbox" value="" id="" />
                                                <label className="form-check-label mt-3" for="">
                                                    Multi-Clipping Path
                                                </label>
                                            </div>
                                        </div>
                                        <div className="col-lg-3 col-md-6">
                                            <div className="form-check">
                                                <input className="form-check-input mt-3" type="checkbox" value="" id="" />
                                                <label className="form-check-label mt-3" for="">
                                                    Ghost Mannequine
                                                </label>
                                            </div>
                                        </div>
                                        <div className="col-lg-3 col-md-6">
                                            <div className="form-check">
                                                <input className="form-check-input mt-3" type="checkbox" value="" id="" />
                                                <label className="form-check-label mt-3" for="">
                                                    Color Change
                                                </label>
                                            </div>
                                        </div>
                                    </div>

                                    <h2 className='mt-5'>Output File Options</h2>
                                    <p className='mb-5'>Choose your desired output file.</p>

                                    <div className="row">

                                        <div className="col-lg-4">
                                            <h4>File Format</h4>
                                            <select class="form-select" aria-label="Default select example">
                                                <option selected>Select Formate</option>
                                                <option value="1">PNG</option>
                                                <option value="2">JPEG</option>
                                                <option value="3">PSD</option>
                                                <option value="4">ROW</option>
                                                <option value="5">PDF</option>
                                                <option value="6">TIFF</option>
                                                <option value="7">NEF</option>
                                                <option value="8">CR2</option>
                                                <option value="9">DNG</option>
                                            </select>
                                        </div>

                                        <div className="col-lg-4">
                                            <h4>Background</h4>
                                            <select class="form-select" aria-label="Default select example">
                                                <option selected>Select Background</option>
                                                <option value="1">Transperant</option>
                                                <option value="2">White</option>
                                                <option value="3">Black</option>
                                            </select>
                                        </div>

                                        <div className="col-lg-4">
                                            <h4>Path</h4>
                                            <select class="form-select" aria-label="Default select example">
                                                <option selected>Select Path</option>
                                                <option value="1">Yes, Include Path</option>
                                                <option value="2">No Path</option>
                                            </select>
                                        </div>

                                    </div>

                                    <h2 className='mt-5'>Upload Files</h2>
                                    <p>Send us your photos and images by uploading them here.</p>

                                    <Form />

                                </div>
                            </div>

                            <div className="col-lg-4">
                                <div className={offerCss.offer_right}>
                                    <h2>How ‘Get a Quote’ works</h2>
                                    <p>After getting your sample files, we will examine the files quality and follow your instructions (if any) accordingly. Our expert designers will work enthusiastically to produce your desired results. Please note that we typically take less than 16 hours for the whole procedure and send you the fully edited file.</p>

                                    <div className={offerCss.divide}></div>

                                    <h3 className='text-center'>Get a Quote Instructions</h3>

                                    <div className={offerCss.offer_right_div}>
                                        <h4>Choose services</h4>
                                        <p>Choose which service you need. If none of the options fit what you’re looking for, specify the service you need in the space provided.</p>
                                    </div>

                                    <div className={offerCss.offer_right_div}>
                                        <h4>Choose Output File Options</h4>
                                        <p>Choose your preferred file format, background type, and if you want us to include the photoshop edit path.</p>
                                    </div>

                                    <div className={offerCss.offer_right_div}>
                                        <h4>Drag & Drop Files</h4>
                                        <p>Drag and drop your files (or click browse) to upload your photos.</p>
                                    </div>

                                    <div className={offerCss.offer_right_div}>
                                        <h4>Contact Details</h4>
                                        <p>Add your contact details so we know where/how to reach you.</p>
                                    </div>

                                    <div className={offerCss.offer_right_div}>
                                        <h4>Get a Quote</h4>
                                        <p>Click the “Get a Quote” button.</p>
                                    </div>

                                    <div className={offerCss.divide}></div>

                                    <h2>Contact us for questions about your free trial</h2>
                                    <p>Contact us if you have questions or clarifications about the Get a Quote and we’ll be happy to address them for you.</p>

                                </div>
                            </div>

                        </div>
                    </div>

                </div>
            </Container>

            <Footer />
        </>
    )
}

export default offer