import React, { useState, useEffect } from "react";
import Head from 'next/head'
// import Image from 'next/image'
import Image from "next/legacy/image"
import Link from "next/link";
import axios from 'axios'

import Container from './Components/container'
// import Index from '../pages/home'

import HomeCss from '../styles/Home.module.css'
import { ReactCompareSlider, ReactCompareSliderImage } from 'react-compare-slider';
import Navbar from "./Components/Navbar";
import Footer from "./Components/footer";


export async function getServerSideProps () {

    try{
        const response = await fetch("http://localhost:3000/api/home/home-all")
        const data = await response.json()
        
        return {
            props : {
                data,
            }
        }

    } catch (err) {
        console.log("err");
    }


}


const Home = ({data}) =>  {

  console.log(data);


    const [ ourWork, setOurWork ] = useState([])
    const [ ourPartner, setOurPartner ] = useState([])


    useEffect(() => {

        axios.get('http://localhost:3000/api/home/home-work')
        .then((work) => {
            setOurWork(work.data)
        })

        axios.get("http://localhost:3000/api/home/our-partner")
        .then((partner) => {
            setOurPartner(partner.data)
        })
        
    }, [])

    const css = {width: "100%", height: "auto" }

  return (


    <>
      <Head>
        <title>Clipping Path Specialist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Navbar />

      <Container>

              <div className='row d-flex align-items-center' id={HomeCss.homePage}>
                    <div className='col-lg-7'>
                        <h1 id={HomeCss.head}>{data.firstTitle}</h1> 
                        <h4>{data.firstTwoTitle}</h4>
                        <h5 className="my-4">{data.firstThreeTitle}</h5>
                        <p className="mb-5">{data.firstPara}</p>

                        <Link href="/get-a-quote" className="btn btn-lg">Get Started <i className="fa-solid fa-arrow-right"></i></Link>
                    </div>
                    <div className="col-lg-5">
                        <Image width="200" height="250" src={data.firstImg} layout="responsive" style={css} alt="" />
                    </div>
                </div>


                <div id={HomeCss.our_feature_section}>
                    <div id={HomeCss.feature_content}>
                        <div className="row d-flex align-items-center">
                            <div className="col-lg-4">
                                <h3>{data.secondTitle}</h3>
                                <p>{data.secondPara}</p>
                            </div>
                            <div className="col-lg-8">
                                <div className="row">
                                    {
                                        data.secondDivs.map((items) => {
                                            return (
                                                <>            
                                                    <div className="col-lg-4 col-md-12">
                                                        <div className={HomeCss.feature_inner_div}>
                                                            <h3>{items.number}</h3>
                                                            <h4>{items.divsTitle}</h4>
                                                            <p>{items.divsPara}</p>
                                                        </div>
                                                    </div>
                                                </>
                                            )
                                        })
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


                <div className="row d-flex align-items-center" id={HomeCss.secondSection}>
                    <div className="col-lg-5 text-center">
                        <Image width="400" height="400" layout="intrinsic" style={css} src={data.thirdImg} alt="" />
                    </div>
                    <div className="col-lg-7">
                        <h3>{data.thirdTitle}</h3>
                        <p className={HomeCss.secondBoldText}><b>{data.thirdParaOne}</b></p>
                        <p className="mb-5">{data.thirdParaTwo}</p>
                        <h4>{data.startingText}</h4>
                    </div>
                </div>


                <div id={HomeCss.certified_section}>
                    <div className="p-4" id={HomeCss.certificate_div}>
                        <div className="row">

                        {
                            data.forthSection.map((items) => {
                                return (
                                    <>        
                                        <div className="col-lg-3 col-md-6">
                                            <div className="row">
                                                <div className="col-2">
                                                    <Image width="200" height="200" layout="intrinsic" style={css} src={items.forthImg} alt="" />
                                                </div>
                                                <div className="col-10">
                                                    <div className={HomeCss.certificate_describe}>
                                                        <h2>{items.forthTitle}</h2>
                                                        <p>{items.forthPara}</p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </>
                                )
                            })
                        }
                        </div>
                    </div>
                </div>


                <div id={HomeCss.color_section}>
                        <div class="row">

                            {
                                data.colorDiv.map((items) => {
                                    let {divClass, divsTitle, divImg} = items
                                    return (
                                        <>            
                                            <div id={HomeCss.padding_less} className="col-lg-4">
                                                <div id={divClass} className="text-center color_1">
                                                    <div className="color_heading">
                                                        <h3 className="pb-5">{items.divTitle}</h3>
                                                    </div>
                                                    <div className="color_img">
                                                        <Image width="200" height="200" layout="intrinsic" style={css} src={items.divImg} alt="" />
                                                    </div>
                                                </div>
                                            </div>
                                        </>
                                    )
                                })
                            }
            
                        </div>
                </div>


                <div id={HomeCss.our_work_section}>
                    <h3 className="mb-5">Here are some of our before-after work samples</h3>

                    <div className="row justify-content-center">

                        {
                          ourWork.map((items) => {
                            return (
                                <>
                                    <div className="col-lg-3 col-md-6">
                                        <div id={HomeCss.allWorks}>
                                            <ReactCompareSlider 
                                                itemOne={<ReactCompareSliderImage className={HomeCss.imageOne} src={items.imageOne} srcSet={items.imageOne} alt="Image one" />}
                                                itemTwo={<ReactCompareSliderImage className={HomeCss.imageTwo} src={items.imageTwo} srcSet={items.imageTwo} alt="Image two" />}
                                            />
                                        </div>
                                            <h4 className="text-center">{items.name}</h4>
                                    </div>
                                </>
                            )
                          })
                        }
                    </div>
                </div>


                <div id={HomeCss.road_map}>
                    <div className="row">
                        <div className="col-lg-5">
                            <h3>{data.sixthLeftTitle}</h3>
                            <p>{data.sixthLeftPara}</p>
                            <Image width="200" height="300" layout="responsive" style={css} src={data.roadMapImg} alt="img" />
                        </div>

                        <div className="col-lg-7">
                            <div className={HomeCss.roadmap_div}>
                                <div className="row d-flex align-items-center">

                                    {
                                        data.sixthRight.map((items) => {
                                            return (
                                                <>
                                                    <div className="col-lg-3 col-md-3 col-sm-12">
                                                        <Image width="150" height="150" layout="intrinsic" style={css} className={HomeCss.roadMapRightImg} src={items.sixthImg} alt="img" />
                                                    </div>
                                                    <div className="col-lg-9 col-md-9 col-sm-12">
                                                        <h4>{items.sixthTitle}</h4>
                                                        <p className="mb-5">{items.sixthPara}</p>
                                                    </div>
                                                    <hr />
                                                </>
                                            )
                                        })
                                    }

                                </div>
                            </div>
                        </div>
                    </div>
                </div>


                <div id={HomeCss.how_do_we_do}>
                    <div className="row text-center">
                        {
                            data.sevenSection.map((items) => {
                                return (
                                    <>            
                                        <div className="col-lg-4">
                                            <Image width="200" height="200" layout="intrinsic" style={css} src={items.sevenImg} alt="img" />
                                            <h4>{items.sevenTitle}</h4>
                                            <p>{items.sevenPara}</p>
                                        </div>
                                    </>
                                )
                            })
                        }
                    </div>
                </div>


                <div id={HomeCss.outsourced_img}>
                    <h3>{data.eightTitle}</h3>
                    <h5>{data.eightPara}</h5>
                    <div className="row py-5 text-center mx-lg-5">

                        {
                            data.eightDivs.map((items) => {
                                return (
                                    <>            
                                        <div className="col-lg-4">
                                            <Image width="200" height="200" layout="intrinsic" style={css} src={items.eightImg} alt="img" />
                                            <p>{items.eightDivPara}</p>
                                        </div>
                                    </>
                                )
                            })
                        }
                    </div>
                    
                    <div className="text-center">
                        <Link href="/get-a-quote" className="btn btn-lg">Get Started <i className="fa-solid fa-arrow-right"></i></Link>
                    </div>
                </div>

                <div id={HomeCss.third_section}>
                    <h3>{data.nineTitle}</h3>
                    <p className={HomeCss.third_section_paragraph}>{data.ninePara}</p>

                    <div className="row d-flex align-items-center">
                        <div className="col-lg-8">
                            <div className="row mt-4">
                                <div className="col-6">
                                    <ul>
                                    {
                                        data.nineFirstLeft.map((items) => {
                                            return (
                                                <>        
                                                    <li>
                                                        <h5>{items.firstLeftTitle}</h5>
                                                        <p>{items.firstLeftPara}</p>
                                                    </li>
                                                </>
                                            )
                                        })
                                    }
                                    </ul>
                                </div>
                                <div className="col-6">
                                    <ul>
                                        {
                                            data.nineLastLeft.map((items) => {
                                                return (
                                                    <>
                                                        <li>
                                                            <h5>{items.lastLeftTitle}</h5>
                                                            <p>{items.lastLeftPara}</p>
                                                        </li>
                                                    </>
                                                )
                                            })
                                        }
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div className="col-lg-4 mt-4 text-center">
                            <Image width="200" height="150" layout="responsive" style={css} src={data.nineImg} alt="img" />
                        </div>
                    </div>
                </div>


                <div id={HomeCss.pricing_section}>
                    <h3>{data.tenTitle}</h3>
                    <p className="mb-5">{data.tenPara}</p>

                    <div className="row text-center">
                        
                        {
                            data.pricingDiv.map((items) => {
                                return (
                                    <>            
                                        <div className="col-lg-4">
                                            <h4>{items.pricingDivTitle}</h4>
                                            <Image width="200" height="200" layout="intrinsic" style={css} id={HomeCss.pricingImage} src={items.pricingImg} alt="img" />
                                            <p>Start at <span>{items.pricingStart}</span>image</p>

                                            <div className={HomeCss.offer}>
                                                <h5>{items.discountTitle}</h5>
                                                <p>{items.discountPara}</p>
                                            </div>
                                        </div>
                                    </>
                                )
                            })
                        }
                    
                    </div>
                </div>


                <div id={HomeCss.customer_review}>
                    <h3>{data.elevenTitle}</h3>
                    <div className="row">

                        {
                            data.elevenDiv.map((items) => {
                                return (
                                    <>   
                                        <div className="col-lg-4">
                                            <div id={HomeCss.review_box}>
                                                <ul>
                                                    <li><i className="fa-solid fa-star"></i></li>    
                                                    <li><i className="fa-solid fa-star"></i></li>    
                                                    <li><i className="fa-solid fa-star"></i></li>    
                                                    <li><i className="fa-solid fa-star"></i></li>    
                                                    <li><i className="fa-solid fa-star"></i></li>    
                                                </ul>       
                                                <h4 className="mt-3">{items.divTitle}</h4>
                                                <p>{items.divPara}</p>
                                                <h4>{items.clientName}</h4>
                                            </div>
                                        </div>
                                    </>
                                )
                            })
                        }
                    </div>
                </div>

                
                <div id={HomeCss.finaly_section}>
                    <div className="row d-flex align-items-center">
                        <div className="col-lg-7">
                            <h3 className="mb-4">{data.twilveTitle}</h3>
                            <p className="mb-5">{data.twilvePara}</p>
                            
                            <Link href="/login" className="btn btn-lg" id={HomeCss.get_start_btn}>Get Started</Link>
                            <Link href="/get-a-quote" className="btn btn-lg" id={HomeCss.get_quote_btn}>Get a Quote</Link>
                        </div>
                        <div className="col-lg-5">
                            <Image width="200" height="150" layout="responsive" style={css} src={data.twilveImg} alt="img" /> 
                        </div>
                    </div>
                </div>

                
                <div id={HomeCss.our_pertner}>
                    <h3>Our Partner</h3>
                    <div className="row text-center">
                        {
                            ourPartner.map((data) => {
                                return(
                                    <>
                                        <div className="col-lg-2">
                                            <Image width="200" height="50" layout="intrinsic" style={css} src={data.img} alt="" />
                                        </div>
                                    </>
                                )
                            })
                        }
                    </div>
                </div>


                <div id={HomeCss.get_in_touch}>
                    <h3>{data.contactTitle}</h3>
                    <div className="row">
                        <div className="col-lg-6">
                            <p>{data.contactPara}</p>

                            <h4>Call us</h4>
                            <p><i className="fa-solid fa-phone"></i> +1 (304) 574-8370</p>

                            <h4>Email</h4>
                            <p className="mb-0"> <i className="fa-solid fa-envelope"></i> info@clippingpathgraphics.com</p>
                            <p><i className="fa-solid fa-envelope"></i> clippingpathgraphics@gmail.com</p>

                            <h4>Visit Us</h4>
                            <p className="mb-0"><i className="fa-solid fa-house"></i> US Office: 10126 ADOBE DRIVE Houston TX 77095</p>
                            <p><i className="fa-solid fa-house"></i> BD Office: Bicon more collage road, Rangpur</p>
                        </div>
                        <div className="col-lg-6">
                            <form action="">
                                <div className="row">
                                    <div className="col-lg-6 mt-3">
                                        <input type="text" className="form-control form-control-lg" placeholder="Name" />
                                    </div>
                                    <div className="col-lg-6 mt-3">
                                        <input type="email" className="form-control form-control-lg" placeholder="Email" />
                                    </div>
                                    <div className="col-lg-12 mt-3">
                                        <input type="text" className="form-control form-control-lg" placeholder="Subject" />
                                    </div>
                                    <div className="col-lg-12 mt-3">
                                        <textarea name="" id="" cols="30" rows="6" className="form-control form-control-lg" placeholder="Message"></textarea>
                                    </div>

                                    <div className="col-lg-12">
                                        <button type="submit" className="btn btn-lg">Send Message</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

        
      </Container>


      <Footer />

    </>
  )
}

export default Home
