import Link from "next/link";
import Head from "next/head"
import Image from "next/legacy/image";

import Container from "../Components/container"
import PricingCss from '../../styles/pricing.module.css'

import Navbar from "../Components/Navbar";
import Footer from "../Components/footer"


export async function getServerSideProps () {

    const res = await fetch("http://localhost:3000/api/pricing")
    const data = await res.json()

    return {
        props : {
            data
        }
    }
}


const price = ({data}) => {

    const css = {width: "100%", height: "auto" }

    return (
        <>
            <Head>
                <title>Pricing</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" type="" href="/img/favicon.png" /> 
            </Head>

            <Navbar />

            <Container>

                <div id={PricingCss.pricing_first}>
                    <div className="row">
                        <div className="col-lg-6">
                            <h1>{data.pricingHeadTitle}</h1>
                            <p>{data.pricingHeadPara}</p>
                        </div>
                        <div className="col-lg-6 text-center">
                            <Image width="350" height="200" layout="intrinsic" style={css} src={data.pricingHeadImg} alt="" />
                        </div>
                    </div>
                </div>

                <div id={PricingCss.pricing_two}>
                    <div className="row justify-content-center">

                        {
                            data.pricingDiv.map((items) => {
                                return (
                                    <>            
                                        <div className="col-lg-6">
                                            <div id={PricingCss.pricing_div} className="mt-4">
                                                <div className="row d-flex align-items-center">
                                                    <div className="col-lg-8 col-sm-12">
                                                        <h3>{items.priceTitle}</h3>
                                                        <div id={PricingCss.price}>
                                                            <p className="mb-0">{items.startText}</p>
                                                            <h3 className="mb-0 text-center">$ {items.price}</h3>
                                                            <p className="mb-0 text-end">{items.perImgText}</p>
                                                        </div>
                                                    </div>
                                                    <div className="col-lg-4 col-sm-12 text-center">
                                                        <Image width="190" height="190" layout="responsive" style={css} id={PricingCss.pricingDivImg} src={items.pricingImg} alt="" />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </>
                                )
                            })
                        }

                    </div>
                </div>

                

            </Container>

            <Footer />
        </>
    )
}

export default price