import Head from 'next/head'
import Link from 'next/link';

import quoteCss from '../../styles/quote.module.css'
import Container from '../Components/container'

import Navbar from "../Components/Navbar";
import Footer from "../Components/footer";
import QuoteForm from '../Components/quote_and_trial_form'

const get_a_quote = () => {
    return (
        <>  
            <Head>
                <title>Get a Quote</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <Navbar />

            <Container>
                <div id={quoteCss.get_a_quote_page}>
                    <div className="row">
                        <div className="col-lg-6">
                            <h1>Request New Quote</h1>
                            <h4>Ready to get started?</h4>
                            <p>Welcome to our image treatment world (Clipping Path Graphics). For justify our quality works you can check out our service by submitting an image to us which is totally free of cost.</p>
                            <h2>INSTRUCTION</h2>
                            <p>Fill in your name, email, Choose the file upload system ( Upload files or shared link ), then select the file location.</p>
                            <p>You can send us JPG, PNG, TIFF, Google Drive shared link also</p>
                            <p>Provide your instruction or opinion on the message box.</p>
                            <p>Finally hit the submit button.</p>
                        </div>
                        <div className="col-lg-6">
                            <QuoteForm />
                        </div>
                    </div>
                </div>
            </Container>

            <Footer />
        </>
    )
}

export default get_a_quote  